# Generated by Django 4.2.7 on 2023-11-28 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('content', models.TextField(null=True)),
                ('link', models.URLField(max_length=2000)),
                ('day', models.CharField(max_length=12)),
            ],
            options={
                'db_table': 'news',
            },
        ),
    ]
